//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursManagement.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToursManagement.Translations.LangResources", typeof(LangResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Tour.
        /// </summary>
        public static string AddToTour {
            get {
                return ResourceManager.GetString("AddToTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Institute.
        /// </summary>
        public static string ArtInstitute {
            get {
                return ResourceManager.GetString("ArtInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braid Line.
        /// </summary>
        public static string BraidLine {
            get {
                return ResourceManager.GetString("BraidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buckingham Fountain.
        /// </summary>
        public static string BuckinghamFountain {
            get {
                return ResourceManager.GetString("BuckinghamFountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy times at a tour-stop.
        /// </summary>
        public static string BusyTimesAtTourStop {
            get {
                return ResourceManager.GetString("BusyTimesAtTourStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Gate.
        /// </summary>
        public static string CloudGate {
            get {
                return ResourceManager.GetString("CloudGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Tourist count this week: 12,570.
        /// </summary>
        public static string EstimatedTouristCountThisWeek {
            get {
                return ResourceManager.GetString("EstimatedTouristCountThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Coffee and Pastries.
        /// </summary>
        public static string HotCoffeeAndPastries {
            get {
                return ResourceManager.GetString("HotCoffeeAndPastries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ut leo augue. Nulla dignissim, velit ut tincidunt sagittis, dui tellus dapibus nisi, ultrices feugiat risus dolor ut quam. Proin bibendum, augue et suscipit venenatis, tellus tellus varius elit, volutpat semper purus dolor eget magna. Etiam sollicitudin dolor id dui feugiat molestie. Praesent consequat bibendum mi, ac lacinia dolor hendrerit et. Aenean a purus quis lacus hendrerit ullamcorper. Donec tristique, nulla sed ullamcorper ultrices, qua [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HotCoffeeAndPastriesDescription {
            get {
                return ResourceManager.GetString("HotCoffeeAndPastriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the morning with a jolt of coffee goodness from this trendy shop. Don&apos;t miss the Caramel Crater pastry, guaranteed to amp up your morning carb count..
        /// </summary>
        public static string HotCoffeeAndPastriesInfo {
            get {
                return ResourceManager.GetString("HotCoffeeAndPastriesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lurie Garden.
        /// </summary>
        public static string LurieGarden {
            get {
                return ResourceManager.GetString("LurieGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paddington&apos;s Pastries.
        /// </summary>
        public static string PaddingtonsPastries {
            get {
                return ResourceManager.GetString("PaddingtonsPastries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Management.
        /// </summary>
        public static string TourManagement {
            get {
                return ResourceManager.GetString("TourManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Stops.
        /// </summary>
        public static string TourStops {
            get {
                return ResourceManager.GetString("TourStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Calendar.
        /// </summary>
        public static string WeeklyCalendar {
            get {
                return ResourceManager.GetString("WeeklyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zekki&apos;s.
        /// </summary>
        public static string Zekkis {
            get {
                return ResourceManager.GetString("Zekkis", resourceCulture);
            }
        }
    }
}
